// Actix Web Framework Adapter (Rust)
import { FrameworkAdapter, FrameworkFeatures, ORMType } from '../../types/frameworks';
import { DatabaseType, AnyDatabaseAdapter } from '../../types/databases';
import { ExportConfig } from '../../types/config';
import { GeneratedFile, toPascalCase, toSnakeCase, CanonicalIR } from '../../types/core';
import { ERSchema } from '../../../schema';

const actixFeatures: FrameworkFeatures = {
  orm: 'SQLx / Diesel / SeaORM',
  migrations: true,
  validation: true,
  authentication: true,
  swagger: true,
  graphql: true,
  testing: true,
  docker: true,
};

export const actixAdapter: FrameworkAdapter = {
  id: 'actix',
  name: 'Actix Web',
  language: 'rust',
  description: 'Powerful, pragmatic, and extremely fast web framework for Rust',
  features: actixFeatures,
  supportedDatabases: ['postgresql', 'mysql', 'sqlite'] as DatabaseType[],
  supportedORMs: ['sqlx', 'diesel', 'sea-orm'] as ORMType[],
  
  generateProject(schema: ERSchema, dbAdapter: AnyDatabaseAdapter, config: ExportConfig): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const projectName = toSnakeCase(config.projectName);
    const base = projectName;
    
    // Cargo.toml
    files.push({
      path: `${base}/Cargo.toml`,
      content: generateCargoToml(projectName, config),
      type: 'config',
    });
    
    // Main entry point
    files.push({
      path: `${base}/src/main.rs`,
      content: generateMainRs(schema, config),
      type: 'config',
    });
    
    // Database configuration
    files.push({
      path: `${base}/src/db.rs`,
      content: generateDbModule(config),
      type: 'config',
    });
    
    // Models
    schema.entities.forEach(entity => {
      files.push({
        path: `${base}/src/models/${toSnakeCase(entity.name)}.rs`,
        content: generateRustModel(entity, config),
        type: 'model',
      });
    });
    
    // Models mod.rs
    files.push({
      path: `${base}/src/models/mod.rs`,
      content: schema.entities.map(e => `pub mod ${toSnakeCase(e.name)};`).join('\n') + '\n\n' +
        schema.entities.map(e => `pub use ${toSnakeCase(e.name)}::*;`).join('\n'),
      type: 'model',
    });
    
    // Handlers (controllers)
    if (config.generateControllers) {
      schema.entities.forEach(entity => {
        files.push({
          path: `${base}/src/handlers/${toSnakeCase(entity.name)}.rs`,
          content: generateRustHandler(entity, config),
          type: 'controller',
        });
      });
      
      files.push({
        path: `${base}/src/handlers/mod.rs`,
        content: schema.entities.map(e => `pub mod ${toSnakeCase(e.name)};`).join('\n'),
        type: 'controller',
      });
    }
    
    // Services
    if (config.generateServices) {
      schema.entities.forEach(entity => {
        files.push({
          path: `${base}/src/services/${toSnakeCase(entity.name)}.rs`,
          content: generateRustService(entity, config),
          type: 'service',
        });
      });
      
      files.push({
        path: `${base}/src/services/mod.rs`,
        content: schema.entities.map(e => `pub mod ${toSnakeCase(e.name)};`).join('\n'),
        type: 'service',
      });
    }
    
    // Error handling
    files.push({
      path: `${base}/src/error.rs`,
      content: generateErrorModule(),
      type: 'other',
    });
    
    // Configuration
    files.push({
      path: `${base}/src/config.rs`,
      content: generateConfigModule(config),
      type: 'config',
    });
    
    // README
    if (config.generateReadme) {
      files.push({
        path: `${base}/README.md`,
        content: generateActixReadme(projectName, config),
        type: 'readme',
      });
    }
    
    return files;
  },
  
  getModelFileName: (entityName) => `${toSnakeCase(entityName)}.rs`,
  getControllerFileName: (entityName) => `${toSnakeCase(entityName)}.rs`,
  getSchemaFileName: (entityName) => `${toSnakeCase(entityName)}.rs`,
  getServiceFileName: (entityName) => `${toSnakeCase(entityName)}.rs`,
  getMigrationFileName: (entityName, timestamp) => `${timestamp}_create_${toSnakeCase(entityName)}.rs`,
};

function generateCargoToml(projectName: string, config: ExportConfig): string {
  return `[package]
name = "${projectName}"
version = "0.1.0"
edition = "2021"
authors = ["Generated by ERForge"]

[dependencies]
# Web framework
actix-web = "4"
actix-rt = "2"
actix-cors = "0.7"

# Async runtime
tokio = { version = "1", features = ["full"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "uuid", "chrono"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Types
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Configuration
dotenv = "0.15"
config = "0.14"

# Validation
validator = { version = "0.18", features = ["derive"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
thiserror = "2"
anyhow = "1"

[dev-dependencies]
actix-rt = "2"
`;
}

function generateMainRs(schema: ERSchema, config: ExportConfig): string {
  const handlerImports = schema.entities.map(e => 
    `use crate::handlers::${toSnakeCase(e.name)}::*;`
  ).join('\n');
  
  const routes = schema.entities.map(e => {
    const name = toSnakeCase(e.name);
    return `            .service(
                web::scope("/${name}s")
                    .route("", web::get().to(get_all_${name}s))
                    .route("", web::post().to(create_${name}))
                    .route("/{id}", web::get().to(get_${name}))
                    .route("/{id}", web::put().to(update_${name}))
                    .route("/{id}", web::delete().to(delete_${name}))
            )`;
  }).join('\n');

  return `use actix_cors::Cors;
use actix_web::{web, App, HttpServer, middleware};
use sqlx::postgres::PgPoolOptions;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

mod config;
mod db;
mod error;
mod handlers;
mod models;
mod services;

${handlerImports}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    // Initialize logging
    tracing_subscriber::registry()
        .with(tracing_subscriber::EnvFilter::new(
            std::env::var("RUST_LOG").unwrap_or_else(|_| "info".into()),
        ))
        .with(tracing_subscriber::fmt::layer())
        .init();

    // Load configuration
    dotenv::dotenv().ok();
    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");
    
    // Create database pool
    let pool = PgPoolOptions::new()
        .max_connections(5)
        .connect(&database_url)
        .await
        .expect("Failed to create pool");

    tracing::info!("Starting server at http://localhost:8080");

    HttpServer::new(move || {
        let cors = Cors::default()
            .allow_any_origin()
            .allow_any_method()
            .allow_any_header();

        App::new()
            .app_data(web::Data::new(pool.clone()))
            .wrap(cors)
            .wrap(middleware::Logger::default())
${routes}
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}
`;
}

function generateDbModule(config: ExportConfig): string {
  return `use sqlx::postgres::PgPool;

pub type DbPool = PgPool;

pub async fn init_pool(database_url: &str) -> Result<DbPool, sqlx::Error> {
    sqlx::postgres::PgPoolOptions::new()
        .max_connections(5)
        .connect(database_url)
        .await
}
`;
}

function generateRustModel(entity: any, config: ExportConfig): string {
  const name = toPascalCase(entity.name);
  const fields = entity.fields.map((f: any) => {
    const rustType = mapToRustType(f.type, f.isNullable);
    return `    pub ${toSnakeCase(f.name)}: ${rustType},`;
  }).join('\n');
  
  const createFields = entity.fields
    .filter((f: any) => !f.isPrimaryKey)
    .map((f: any) => {
      const rustType = mapToRustType(f.type, f.isNullable);
      return `    pub ${toSnakeCase(f.name)}: ${rustType},`;
    }).join('\n');

  return `use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;
use validator::Validate;

/// ${name} entity
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ${name} {
${fields}
}

/// DTO for creating a new ${name}
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct Create${name} {
${createFields}
}

/// DTO for updating an existing ${name}
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct Update${name} {
${entity.fields.filter((f: any) => !f.isPrimaryKey).map((f: any) => {
  const rustType = mapToRustType(f.type, true); // All optional for updates
  return `    pub ${toSnakeCase(f.name)}: ${rustType},`;
}).join('\n')}
}

impl ${name} {
    /// Create a new ${name} from a Create DTO
    pub fn from_create(dto: Create${name}) -> Self {
        Self {
            id: Uuid::new_v4(),
${entity.fields.filter((f: any) => !f.isPrimaryKey).map((f: any) => {
  return `            ${toSnakeCase(f.name)}: dto.${toSnakeCase(f.name)},`;
}).join('\n')}
        }
    }
}
`;
}

function generateRustHandler(entity: any, config: ExportConfig): string {
  const name = toPascalCase(entity.name);
  const snakeName = toSnakeCase(entity.name);
  
  return `use actix_web::{web, HttpResponse, Result};
use sqlx::PgPool;
use uuid::Uuid;

use crate::error::AppError;
use crate::models::${snakeName}::{${name}, Create${name}, Update${name}};
use crate::services::${snakeName}::${name}Service;

/// Get all ${name}s
pub async fn get_all_${snakeName}s(
    pool: web::Data<PgPool>,
) -> Result<HttpResponse, AppError> {
    let items = ${name}Service::find_all(pool.get_ref()).await?;
    Ok(HttpResponse::Ok().json(items))
}

/// Get a single ${name} by ID
pub async fn get_${snakeName}(
    pool: web::Data<PgPool>,
    path: web::Path<Uuid>,
) -> Result<HttpResponse, AppError> {
    let id = path.into_inner();
    let item = ${name}Service::find_by_id(pool.get_ref(), id).await?;
    
    match item {
        Some(item) => Ok(HttpResponse::Ok().json(item)),
        None => Ok(HttpResponse::NotFound().finish()),
    }
}

/// Create a new ${name}
pub async fn create_${snakeName}(
    pool: web::Data<PgPool>,
    body: web::Json<Create${name}>,
) -> Result<HttpResponse, AppError> {
    let item = ${name}Service::create(pool.get_ref(), body.into_inner()).await?;
    Ok(HttpResponse::Created().json(item))
}

/// Update an existing ${name}
pub async fn update_${snakeName}(
    pool: web::Data<PgPool>,
    path: web::Path<Uuid>,
    body: web::Json<Update${name}>,
) -> Result<HttpResponse, AppError> {
    let id = path.into_inner();
    let item = ${name}Service::update(pool.get_ref(), id, body.into_inner()).await?;
    
    match item {
        Some(item) => Ok(HttpResponse::Ok().json(item)),
        None => Ok(HttpResponse::NotFound().finish()),
    }
}

/// Delete a ${name}
pub async fn delete_${snakeName}(
    pool: web::Data<PgPool>,
    path: web::Path<Uuid>,
) -> Result<HttpResponse, AppError> {
    let id = path.into_inner();
    let deleted = ${name}Service::delete(pool.get_ref(), id).await?;
    
    if deleted {
        Ok(HttpResponse::NoContent().finish())
    } else {
        Ok(HttpResponse::NotFound().finish())
    }
}
`;
}

function generateRustService(entity: any, config: ExportConfig): string {
  const name = toPascalCase(entity.name);
  const snakeName = toSnakeCase(entity.name);
  const tableName = config.tablePluralizer ? `${snakeName}s` : snakeName;
  
  return `use sqlx::PgPool;
use uuid::Uuid;

use crate::error::AppError;
use crate::models::${snakeName}::{${name}, Create${name}, Update${name}};

pub struct ${name}Service;

impl ${name}Service {
    /// Find all ${name}s
    pub async fn find_all(pool: &PgPool) -> Result<Vec<${name}>, AppError> {
        let items = sqlx::query_as::<_, ${name}>(
            "SELECT * FROM ${tableName}"
        )
        .fetch_all(pool)
        .await?;
        
        Ok(items)
    }

    /// Find a ${name} by ID
    pub async fn find_by_id(pool: &PgPool, id: Uuid) -> Result<Option<${name}>, AppError> {
        let item = sqlx::query_as::<_, ${name}>(
            "SELECT * FROM ${tableName} WHERE id = $1"
        )
        .bind(id)
        .fetch_optional(pool)
        .await?;
        
        Ok(item)
    }

    /// Create a new ${name}
    pub async fn create(pool: &PgPool, input: Create${name}) -> Result<${name}, AppError> {
        let entity = ${name}::from_create(input);
        
        sqlx::query(
            "INSERT INTO ${tableName} (id${entity.fields.filter((f: any) => !f.isPrimaryKey).map((f: any) => `, ${toSnakeCase(f.name)}`).join('')}) VALUES ($1${entity.fields.filter((f: any) => !f.isPrimaryKey).map((_: any, i: number) => `, $${i + 2}`).join('')})"
        )
        .bind(&entity.id)
${entity.fields.filter((f: any) => !f.isPrimaryKey).map((f: any) => `        .bind(&entity.${toSnakeCase(f.name)})`).join('\n')}
        .execute(pool)
        .await?;
        
        Ok(entity)
    }

    /// Update an existing ${name}
    pub async fn update(pool: &PgPool, id: Uuid, input: Update${name}) -> Result<Option<${name}>, AppError> {
        // Build dynamic update query based on provided fields
        let result = sqlx::query(
            "UPDATE ${tableName} SET updated_at = NOW() WHERE id = $1"
        )
        .bind(id)
        .execute(pool)
        .await?;
        
        if result.rows_affected() == 0 {
            return Ok(None);
        }
        
        Self::find_by_id(pool, id).await
    }

    /// Delete a ${name}
    pub async fn delete(pool: &PgPool, id: Uuid) -> Result<bool, AppError> {
        let result = sqlx::query("DELETE FROM ${tableName} WHERE id = $1")
            .bind(id)
            .execute(pool)
            .await?;
        
        Ok(result.rows_affected() > 0)
    }
}
`;
}

function generateErrorModule(): string {
  return `use actix_web::{HttpResponse, ResponseError};
use std::fmt;

#[derive(Debug)]
pub enum AppError {
    Database(sqlx::Error),
    Validation(String),
    NotFound(String),
    Conflict(String),
    Internal(String),
}

impl fmt::Display for AppError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            AppError::Database(e) => write!(f, "Database error: {}", e),
            AppError::Validation(msg) => write!(f, "Validation error: {}", msg),
            AppError::NotFound(msg) => write!(f, "Not found: {}", msg),
            AppError::Conflict(msg) => write!(f, "Conflict: {}", msg),
            AppError::Internal(msg) => write!(f, "Internal error: {}", msg),
        }
    }
}

impl std::error::Error for AppError {}

impl ResponseError for AppError {
    fn error_response(&self) -> HttpResponse {
        match self {
            AppError::Database(_) => HttpResponse::InternalServerError().json(serde_json::json!({
                "error": "Database error"
            })),
            AppError::Validation(msg) => HttpResponse::BadRequest().json(serde_json::json!({
                "error": msg
            })),
            AppError::NotFound(msg) => HttpResponse::NotFound().json(serde_json::json!({
                "error": msg
            })),
            AppError::Conflict(msg) => HttpResponse::Conflict().json(serde_json::json!({
                "error": msg
            })),
            AppError::Internal(msg) => HttpResponse::InternalServerError().json(serde_json::json!({
                "error": msg
            })),
        }
    }
}

impl From<sqlx::Error> for AppError {
    fn from(err: sqlx::Error) -> Self {
        AppError::Database(err)
    }
}
`;
}

function generateConfigModule(config: ExportConfig): string {
  return `use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Config {
    pub database_url: String,
    pub host: String,
    pub port: u16,
}

impl Config {
    pub fn from_env() -> Result<Self, config::ConfigError> {
        config::Config::builder()
            .add_source(config::Environment::default())
            .set_default("host", "127.0.0.1")?
            .set_default("port", 8080)?
            .build()?
            .try_deserialize()
    }
}
`;
}

function generateActixReadme(projectName: string, config: ExportConfig): string {
  return `# ${projectName}

A Rust API generated by ERForge using Actix Web.

## Requirements

- Rust 1.70+
- PostgreSQL 14+

## Setup

1. Create a \`.env\` file:
\`\`\`
DATABASE_URL=postgresql://user:password@localhost:5432/${projectName}
RUST_LOG=info
\`\`\`

2. Create the database:
\`\`\`bash
createdb ${projectName}
\`\`\`

3. Run migrations:
\`\`\`bash
sqlx migrate run
\`\`\`

## Running

\`\`\`bash
cargo run
\`\`\`

The API will be available at \`http://localhost:8080\`.

## Development

\`\`\`bash
cargo watch -x run
\`\`\`

## Testing

\`\`\`bash
cargo test
\`\`\`
`;
}

function mapToRustType(type: string, nullable: boolean): string {
  const mapping: Record<string, string> = {
    string: 'String',
    text: 'String',
    int: 'i32',
    integer: 'i32',
    float: 'f64',
    boolean: 'bool',
    date: 'chrono::NaiveDate',
    datetime: 'DateTime<Utc>',
    uuid: 'Uuid',
    json: 'serde_json::Value',
    decimal: 'rust_decimal::Decimal',
    bigint: 'i64',
    binary: 'Vec<u8>',
  };
  
  const rustType = mapping[type] || 'String';
  return nullable ? `Option<${rustType}>` : rustType;
}
