// Python FastAPI + SQLAlchemy Code Generator
// Generates a complete, ready-to-run backend project from ERSchema

import { ERSchema, Entity, Field, FIELD_TYPES, Relation } from './schema';

const toSnakeCase = (str: string): string => {
  return str
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
    .replace(/\s+/g, '_')
    .replace(/-/g, '_');
};

const toPascalCase = (str: string): string => {
  return str
    .replace(/[-_\s]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
    .replace(/^./, (c) => c.toUpperCase());
};

const getPythonType = (fieldType: string): string => {
  const typeInfo = FIELD_TYPES.find(t => t.value === fieldType);
  return typeInfo?.pythonType || 'str';
};

const getSQLAlchemyType = (fieldType: string): string => {
  const typeMap: Record<string, string> = {
    'integer': 'Integer',
    'string': 'String(255)',
    'text': 'Text',
    'boolean': 'Boolean',
    'float': 'Float',
    'datetime': 'DateTime',
    'date': 'Date',
    'uuid': 'String(36)',
  };
  return typeMap[fieldType] || 'String(255)';
};

const getPydanticType = (fieldType: string, isNullable: boolean): string => {
  const typeMap: Record<string, string> = {
    'integer': 'int',
    'string': 'str',
    'text': 'str',
    'boolean': 'bool',
    'float': 'float',
    'datetime': 'datetime',
    'date': 'date',
    'uuid': 'str',
  };
  const baseType = typeMap[fieldType] || 'str';
  return isNullable ? `Optional[${baseType}]` : baseType;
};

// Generate models.py
export const generateModels = (schema: ERSchema): string => {
  const imports = `"""
SQLAlchemy Models
Auto-generated by ERForge
"""

from sqlalchemy import Column, Integer, String, Text, Boolean, Float, DateTime, Date, ForeignKey
from sqlalchemy.orm import relationship
from database import Base
from datetime import datetime, date

`;

  const models = schema.entities.map(entity => {
    const className = toPascalCase(entity.name);
    const tableName = toSnakeCase(entity.name);
    
    const fields = entity.fields.map(field => {
      const columnName = toSnakeCase(field.name);
      const sqlType = getSQLAlchemyType(field.type);
      
      const constraints: string[] = [];
      if (field.isPrimaryKey) {
        constraints.push('primary_key=True');
        if (field.type === 'integer') {
          constraints.push('autoincrement=True');
        }
      }
      if (!field.isNullable && !field.isPrimaryKey) {
        constraints.push('nullable=False');
      }
      if (field.isUnique && !field.isPrimaryKey) {
        constraints.push('unique=True');
      }
      
      // Handle foreign keys
      if (field.isForeignKey && field.foreignKeyRef) {
        const targetEntity = schema.entities.find(e => e.id === field.foreignKeyRef?.entityId);
        if (targetEntity) {
          const targetTable = toSnakeCase(targetEntity.name);
          const targetField = targetEntity.fields.find(f => f.id === field.foreignKeyRef?.fieldId);
          if (targetField) {
            constraints.push(`ForeignKey('${targetTable}.${toSnakeCase(targetField.name)}')`);
          }
        }
      }
      
      const constraintStr = constraints.length > 0 ? `, ${constraints.join(', ')}` : '';
      return `    ${columnName} = Column(${sqlType}${constraintStr})`;
    }).join('\n');

    // Add relationships based on relations
    const relationships: string[] = [];
    schema.relations.forEach(rel => {
      if (rel.targetEntityId === entity.id) {
        const sourceEntity = schema.entities.find(e => e.id === rel.sourceEntityId);
        if (sourceEntity) {
          const relName = toSnakeCase(sourceEntity.name) + 's';
          relationships.push(`    ${relName} = relationship("${toPascalCase(sourceEntity.name)}", back_populates="${toSnakeCase(entity.name)}")`);
        }
      }
      if (rel.sourceEntityId === entity.id) {
        const targetEntity = schema.entities.find(e => e.id === rel.targetEntityId);
        if (targetEntity) {
          relationships.push(`    ${toSnakeCase(targetEntity.name)} = relationship("${toPascalCase(targetEntity.name)}", back_populates="${toSnakeCase(entity.name)}s")`);
        }
      }
    });

    const relationshipStr = relationships.length > 0 ? '\n\n' + relationships.join('\n') : '';

    return `
class ${className}(Base):
    """${entity.name} model"""
    __tablename__ = "${tableName}"

${fields}${relationshipStr}

    def __repr__(self):
        return f"<${className}(id={self.id})>"
`;
  }).join('\n');

  return imports + models;
};

// Generate schemas.py (Pydantic models)
export const generateSchemas = (schema: ERSchema): string => {
  const imports = `"""
Pydantic Schemas
Auto-generated by ERForge
"""

from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime, date

`;

  const schemas = schema.entities.map(entity => {
    const className = toPascalCase(entity.name);
    
    // Base schema (for creation)
    const createFields = entity.fields
      .filter(f => !f.isPrimaryKey)
      .map(field => {
        const fieldName = toSnakeCase(field.name);
        const fieldType = getPydanticType(field.type, field.isNullable);
        const defaultValue = field.isNullable ? ' = None' : '';
        return `    ${fieldName}: ${fieldType}${defaultValue}`;
      }).join('\n');

    // Response schema (includes ID)
    const responseFields = entity.fields
      .map(field => {
        const fieldName = toSnakeCase(field.name);
        const fieldType = getPydanticType(field.type, field.isNullable);
        const defaultValue = field.isNullable ? ' = None' : '';
        return `    ${fieldName}: ${fieldType}${defaultValue}`;
      }).join('\n');

    return `
# ${className} Schemas
class ${className}Base(BaseModel):
    """Base schema for ${className}"""
${createFields || '    pass'}


class ${className}Create(${className}Base):
    """Schema for creating a new ${className}"""
    pass


class ${className}Update(BaseModel):
    """Schema for updating a ${className}"""
${createFields.replace(/: /g, ': Optional[').replace(/\n/g, '] = None\n')}


class ${className}Response(${className}Base):
    """Schema for ${className} response"""
${responseFields}

    class Config:
        from_attributes = True
`;
  }).join('\n');

  return imports + schemas;
};

// Generate crud.py
export const generateCrud = (schema: ERSchema): string => {
  const imports = `"""
CRUD Operations
Auto-generated by ERForge
"""

from sqlalchemy.orm import Session
from typing import List, Optional
import models
import schemas

`;

  const cruds = schema.entities.map(entity => {
    const className = toPascalCase(entity.name);
    const varName = toSnakeCase(entity.name);
    const pkField = entity.fields.find(f => f.isPrimaryKey);
    const pkName = pkField ? toSnakeCase(pkField.name) : 'id';

    return `
# ${className} CRUD Operations
def get_${varName}(db: Session, ${varName}_id: int) -> Optional[models.${className}]:
    """Get a single ${varName} by ID"""
    return db.query(models.${className}).filter(models.${className}.${pkName} == ${varName}_id).first()


def get_${varName}s(db: Session, skip: int = 0, limit: int = 100) -> List[models.${className}]:
    """Get multiple ${varName}s with pagination"""
    return db.query(models.${className}).offset(skip).limit(limit).all()


def create_${varName}(db: Session, ${varName}: schemas.${className}Create) -> models.${className}:
    """Create a new ${varName}"""
    db_${varName} = models.${className}(**${varName}.model_dump())
    db.add(db_${varName})
    db.commit()
    db.refresh(db_${varName})
    return db_${varName}


def update_${varName}(db: Session, ${varName}_id: int, ${varName}: schemas.${className}Update) -> Optional[models.${className}]:
    """Update an existing ${varName}"""
    db_${varName} = get_${varName}(db, ${varName}_id)
    if db_${varName}:
        update_data = ${varName}.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(db_${varName}, key, value)
        db.commit()
        db.refresh(db_${varName})
    return db_${varName}


def delete_${varName}(db: Session, ${varName}_id: int) -> bool:
    """Delete a ${varName}"""
    db_${varName} = get_${varName}(db, ${varName}_id)
    if db_${varName}:
        db.delete(db_${varName})
        db.commit()
        return True
    return False
`;
  }).join('\n');

  return imports + cruds;
};

// Generate main.py (FastAPI routes)
export const generateMain = (schema: ERSchema): string => {
  const entityImports = schema.entities.map(e => {
    const className = toPascalCase(e.name);
    const varName = toSnakeCase(e.name);
    return { className, varName };
  });

  const imports = `"""
FastAPI Main Application
Auto-generated by ERForge

Run with: uvicorn main:app --reload
API Docs: http://localhost:8000/docs
"""

from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from typing import List

import models
import schemas
import crud
from database import engine, get_db

# Create database tables
models.Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="${schema.name} API",
    description="Auto-generated API by ERForge",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def root():
    """API Health Check"""
    return {"message": "Welcome to ${schema.name} API", "status": "healthy"}

`;

  const routes = schema.entities.map(entity => {
    const className = toPascalCase(entity.name);
    const varName = toSnakeCase(entity.name);
    const routeName = varName.replace(/_/g, '-');

    return `
# ============================================
# ${className} Routes
# ============================================

@app.post("/${routeName}s/", response_model=schemas.${className}Response, tags=["${className}"])
def create_${varName}(${varName}: schemas.${className}Create, db: Session = Depends(get_db)):
    """Create a new ${varName}"""
    return crud.create_${varName}(db=db, ${varName}=${varName})


@app.get("/${routeName}s/", response_model=List[schemas.${className}Response], tags=["${className}"])
def read_${varName}s(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """Get all ${varName}s with pagination"""
    return crud.get_${varName}s(db, skip=skip, limit=limit)


@app.get("/${routeName}s/{${varName}_id}", response_model=schemas.${className}Response, tags=["${className}"])
def read_${varName}(${varName}_id: int, db: Session = Depends(get_db)):
    """Get a single ${varName} by ID"""
    db_${varName} = crud.get_${varName}(db, ${varName}_id=id)
    if db_${varName} is None:
        raise HTTPException(status_code=404, detail="${className} not found")
    return db_${varName}


@app.put("/${routeName}s/{${varName}_id}", response_model=schemas.${className}Response, tags=["${className}"])
def update_${varName}(${varName}_id: int, ${varName}: schemas.${className}Update, db: Session = Depends(get_db)):
    """Update an existing ${varName}"""
    db_${varName} = crud.update_${varName}(db, ${varName}_id=${varName}_id, ${varName}=${varName})
    if db_${varName} is None:
        raise HTTPException(status_code=404, detail="${className} not found")
    return db_${varName}


@app.delete("/${routeName}s/{${varName}_id}", tags=["${className}"])
def delete_${varName}(${varName}_id: int, db: Session = Depends(get_db)):
    """Delete a ${varName}"""
    success = crud.delete_${varName}(db, ${varName}_id=${varName}_id)
    if not success:
        raise HTTPException(status_code=404, detail="${className} not found")
    return {"message": "${className} deleted successfully"}
`;
  }).join('\n');

  return imports + routes;
};

// Generate database.py
export const generateDatabase = (): string => {
  return `"""
Database Configuration
Auto-generated by ERForge
"""

from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# SQLite database URL - change this for production
SQLALCHEMY_DATABASE_URL = "sqlite:///./app.db"

# Create engine
engine = create_engine(
    SQLALCHEMY_DATABASE_URL,
    connect_args={"check_same_thread": False}  # SQLite specific
)

# Create session factory
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Create base class for models
Base = declarative_base()


def get_db():
    """
    Dependency that creates a new database session for each request
    and closes it when the request is finished.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
`;
};

// Generate requirements.txt
export const generateRequirements = (): string => {
  return `# Python Dependencies
# Auto-generated by ERForge

fastapi>=0.104.0
uvicorn[standard]>=0.24.0
sqlalchemy>=2.0.0
pydantic>=2.5.0
python-multipart>=0.0.6
`;
};

// Generate README.md
export const generateReadme = (schema: ERSchema): string => {
  const entityList = schema.entities.map(e => `- **${e.name}**: ${e.fields.length} fields`).join('\n');
  
  return `# ${schema.name} API

Auto-generated backend by **ERForge** - Visual Database Designer

## 🚀 Quick Start

### Prerequisites
- Python 3.9+
- pip

### Installation

\`\`\`bash
# Create virtual environment (recommended)
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate

# Install dependencies
pip install -r requirements.txt
\`\`\`

### Run the Server

\`\`\`bash
uvicorn main:app --reload
\`\`\`

The API will be available at: **http://localhost:8000**

## 📚 API Documentation

- **Swagger UI**: http://localhost:8000/docs
- **ReDoc**: http://localhost:8000/redoc

## 📦 Entities

${entityList}

## 🗄️ Database

This project uses **SQLite** by default. The database file (\`app.db\`) will be created automatically when you first run the server.

To use a different database, update the \`SQLALCHEMY_DATABASE_URL\` in \`database.py\`.

## 📁 Project Structure

\`\`\`
├── main.py          # FastAPI application and routes
├── models.py        # SQLAlchemy ORM models
├── schemas.py       # Pydantic validation schemas
├── crud.py          # Database operations
├── database.py      # Database configuration
├── requirements.txt # Python dependencies
└── README.md        # This file
\`\`\`

## 🔧 Customization

Feel free to modify any of these files to add:
- Custom validation logic
- Additional endpoints
- Authentication/authorization
- More complex queries

---

Generated with ❤️ by [ERForge](https://erforge.dev)
`;
};

// Main export function that generates all files
export interface GeneratedFile {
  path: string;
  content: string;
}

export const generateProject = (schema: ERSchema): GeneratedFile[] => {
  return [
    { path: 'main.py', content: generateMain(schema) },
    { path: 'models.py', content: generateModels(schema) },
    { path: 'schemas.py', content: generateSchemas(schema) },
    { path: 'crud.py', content: generateCrud(schema) },
    { path: 'database.py', content: generateDatabase() },
    { path: 'requirements.txt', content: generateRequirements() },
    { path: 'README.md', content: generateReadme(schema) },
    { path: 'schema.json', content: JSON.stringify(schema, null, 2) },
  ];
};
